# Generated by Django 4.0.4 on 2022-05-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='customer_notes',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='customer_settings',
        ),
    ]
