# Generated by Django 4.0.4 on 2022-05-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_customerdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
    ]
